spring.application.name=basicos

management.endpoints.web.exposure.include=health,info,*
management.endpoints.web.exposure.exclude=health
management.info.env.enabled=true

info.app.name= mi super app
info.app.description= app para aprender
info.app.version=0.0.1

spring.security.user.name=jordy
spring.security.user.password=meliora321

# Propiedades personalizadas
elgrande.nombreEmpresa.nombre = Jordy
url.nombreEmpresa = www.jpord.com

#cambiar puerto
server.port=8182
#cambiando la path (no mas '/' ahora sera '/jordy/')
server.servlet.context-path=/jordy